receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  resource:
    attributes:
    - key: service.namespace
      value: "Meminator"
      action: insert
    - key: deployment.environment
      value: "test"
      action: insert

connectors:
  spanmetrics:
    namespace: span.metrics

exporters:
  debug:

  otlphttp:
    endpoint: https://otlp-gateway-prod-gb-south-1.grafana.net/otlp
    headers:
      Authorization: Basic MTE2ODc0NDpnbGNfZXlKdklqb2lNVE0wTURNeU15SXNJbTRpT2lKemRHRmpheTB4TVRZNE56UTBMVzkwYkhBdGQzSnBkR1V0YjNSc2NDMWxibVJ3YjJsdWRDSXNJbXNpT2lJMk1ESnRhWE5XTlU1cFlXVjVPREJuYmpreFlUQk1hak1pTENKdElqcDdJbklpT2lKd2NtOWtMV2RpTFhOdmRYUm9MVEVpZlgwPQ==
    tls:
      insecure: false
      insecure_skip_verify: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,resource]
      exporters: [otlphttp, spanmetrics]
    metrics:
      receivers: [spanmetrics]
      processors: [batch]
      exporters: [otlphttp]
