services:

  otel-col-contrib:
    image: otel/opentelemetry-collector-contrib:latest
    pull_policy: always
    restart: on-failure
    volumes:
      - ./otel-col-contrib/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
      - "1777:1777"
      - "55679:55679"

  backend-for-frontend:
    build:
      context: services/backend-for-frontend-java
      dockerfile: Dockerfile
    image: backend-for-frontend-java:latest
    ports:
      - "10115"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:10115/actuator/health || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 24

  image-picker:
    build:
      context: services/image-picker-java
      dockerfile: Dockerfile
    image: image-picker-java:latest
    ports:
      - "10116"
    environment:
      BUCKET_NAME: random-pictures

  meminator:
    build:
      context: services/meminator-java
      dockerfile: Dockerfile
    image: meminator-java:latest
    ports:
      - "10117"

  phrase-picker:
    build:
      context: services/phrase-picker-java
      dockerfile: Dockerfile
    image: phrase-picker-java:latest
    ports:
      - "10118"

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
    image: web:latest
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114"
    depends_on:
      backend-for-frontend:
        condition: service_healthy
      image-picker:
        condition: service_started
      meminator:
        condition: service_started
      phrase-picker:
        condition: service_started
      otel-col-contrib:
        condition: service_started
