services:
  backend-for-frontend:
    build:
      context: services/backend-for-frontend-nodejs
      dockerfile: Dockerfile
    image: backend-for-frontend-nodejs:latest
    ports:
      - "10115"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:10115/health || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 24

  image-picker:
    build:
      context: services/image-picker-nodejs
      dockerfile: Dockerfile
    image: image-picker-nodejs:latest
    ports:
      - "10116" 
    environment:
      BUCKET_NAME: random-pictures

  meminator:
    build:
      context: services/meminator-nodejs
      dockerfile: Dockerfile
    image: meminator-nodejs:latest
    ports:
      - "10117" 

  phrase-picker:
    build:
      context: services/phrase-picker-nodejs
      dockerfile: Dockerfile
    image: phrase-picker-nodejs:latest
    ports:
      - "10118"

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
    image: web:latest
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114"
    depends_on:
      backend-for-frontend:
        condition: service_healthy
      image-picker:
        condition: service_started
      meminator:
        condition: service_started
      phrase-picker:
        condition: service_started        
